In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
vector = torch.tensor([[],[]])
vector.ndim
vector.shape

torch.Size([2, 0])

In [ ]:
matrix = torch.tensor([[1, 2],[3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
range = torch.arange(start = 1, end = 10, step = 1)
range

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.zeros_like(range)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
tensor = torch.rand(3)
print(tensor @ tensor)
print(tensor)
print(torch.tensor([1,2,3]).shape)

tensor(0.9159)
tensor([0.6386, 0.5025, 0.5055])
torch.Size([3])


In [ ]:
torch.rand(1, 2, 3).T.shape

<ipython-input-10-da2f33edd106>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3675.)
  torch.rand(1, 2, 3).T.shape


torch.Size([3, 2, 1])

In [ ]:
test = torch.arange(0, 11)
torch.max(test)

tensor(10)

In [ ]:
temp = torch.arange(0,12)
temp = temp.view(2, 2, 3)
temp[0:-1]

tensor([[[0, 1, 2],
         [3, 4, 5]]])

In [50]:
temp = torch.arange(1, 10)
different = temp.view(3, 3)
temp[0] = 10
print(different, temp)

tensor([[10,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]) tensor([10,  2,  3,  4,  5,  6,  7,  8,  9])
