In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install tensorflow-datasets

In [ ]:
import tensorflow_datasets as tfds

In [ ]:
dataset, info = tfds.load('nsynth', with_info=True)

print(info)

Dl Completed...:   0%|          | 0/1069 [00:00<?, ? file/s]

Dataset nsynth downloaded and prepared to /root/tensorflow_datasets/nsynth/full/2.3.3. Subsequent calls will reuse this data.
tfds.core.DatasetInfo(
    name='nsynth',
    full_name='nsynth/full/2.3.3',
    description="""
    The NSynth Dataset is an audio dataset containing ~300k musical notes, each with
    a unique pitch, timbre, and envelope. Each note is annotated with three
    additional pieces of information based on a combination of human evaluation and
    heuristic algorithms: Source, Family, and Qualities.
    """,
    config_description="""
    Full NSynth Dataset is split into train, valid, and test sets, with no
    instruments overlapping between the train set and the valid/test sets.
    
    """,
    homepage='https://g.co/magenta/nsynth-dataset',
    data_dir='/root/tensorflow_datasets/nsynth/full/incomplete.O9H0NI_2.3.3/',
    file_format=tfrecord,
    download_size=73.07 GiB,
    dataset_size=73.09 GiB,
    features=FeaturesDict({
        'audio': Audio(shape=(640

In [ ]:
import tensorflow_datasets as tfds
import os
import librosa
import soundfile as sf

In [ ]:
import os
import librosa
import tensorflow as tf
import tensorflow_datasets as tfds

# Load the NSynth dataset
dataset, info = tfds.load('nsynth', with_info=True)

# Create a directory to save the audio files
os.makedirs('nsynth_audio', exist_ok=True)

# Iterate through the dataset and save the audio files
i = 0
for example in dataset['test']:
  if i > 0:
    break
  i += 1
  # for key in example.keys():
  #   print(key + ":")
  #   print(example[key])
  # print(type(example["instrument"]))
  print(example["instrument"]["family"])
  for key in example.keys():
    print(key)
  if example["instrument"]["family"] == 3:
    print("YAUR YAUR YAUR")
  print(example)
  print("--------------------------")
  for key in example["instrument"].keys():
    print(key)
  print(example["instrument"]["source"])

tf.Tensor(3, shape=(), dtype=int64)
audio
id
instrument
pitch
qualities
velocity
YAUR YAUR YAUR
{'audio': <tf.Tensor: shape=(64000,), dtype=float32, numpy=
array([-0.00042818,  0.00042927, -0.0004303 , ...,  0.00042468,
       -0.00042588,  0.00042705], dtype=float32)>, 'id': <tf.Tensor: shape=(), dtype=string, numpy=b'guitar_acoustic_014-054-100'>, 'instrument': {'family': <tf.Tensor: shape=(), dtype=int64, numpy=3>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=322>, 'source': <tf.Tensor: shape=(), dtype=int64, numpy=0>}, 'pitch': <tf.Tensor: shape=(), dtype=int64, numpy=54>, 'qualities': {'bright': <tf.Tensor: shape=(), dtype=bool, numpy=False>, 'dark': <tf.Tensor: shape=(), dtype=bool, numpy=False>, 'distortion': <tf.Tensor: shape=(), dtype=bool, numpy=False>, 'fast_decay': <tf.Tensor: shape=(), dtype=bool, numpy=False>, 'long_release': <tf.Tensor: shape=(), dtype=bool, numpy=False>, 'multiphonic': <tf.Tensor: shape=(), dtype=bool, numpy=False>, 'nonlinear_env': <tf.Tensor: sha

In [75]:
import torch
import numpy as np

# Searches for files to download (0 means acoustic and 8 means strings)
i = 0
numpy_temp = 0
for example in dataset['train']:
  if i >= 5:
    break
  if (example["instrument"]["source"] == 0) and (example["instrument"]["family"] == 8):
    i += 1
    print(f'pitch: {example["pitch"]}')
    print(f'velocity: {example["velocity"]}')
    for key in example['instrument'].keys():
      print(f"{key}:{example['instrument'][key]}")
    print(tf.shape(example['audio']))
    print(example["audio"])
    tf_tensor = example['audio']
    print(tf_tensor.shape)
    numpy_temp = tf_tensor.numpy()
    print(numpy_temp)
    torch_tensor = torch.from_numpy(numpy_temp)
    print(torch_tensor)
    print(torch_tensor.shape)

pitch: 37
velocity: 75
family:8
label:857
source:0
tf.Tensor([64000], shape=(1,), dtype=int32)
tf.Tensor(
[ 1.9434298e-08 -2.7342580e-08  3.6482561e-08 ...  0.0000000e+00
  0.0000000e+00  0.0000000e+00], shape=(64000,), dtype=float32)
(64000,)
[ 1.9434298e-08 -2.7342580e-08  3.6482561e-08 ...  0.0000000e+00
  0.0000000e+00  0.0000000e+00]
tensor([ 1.9434e-08, -2.7343e-08,  3.6483e-08,  ...,  0.0000e+00,
         0.0000e+00,  0.0000e+00])
torch.Size([64000])
pitch: 97
velocity: 25
family:8
label:885
source:0
tf.Tensor([64000], shape=(1,), dtype=int32)
tf.Tensor(
[-3.0074493e-06  5.0031449e-05  6.0470554e-04 ...  0.0000000e+00
  0.0000000e+00  0.0000000e+00], shape=(64000,), dtype=float32)
(64000,)
[-3.0074493e-06  5.0031449e-05  6.0470554e-04 ...  0.0000000e+00
  0.0000000e+00  0.0000000e+00]
tensor([-3.0074e-06,  5.0031e-05,  6.0471e-04,  ...,  0.0000e+00,
         0.0000e+00,  0.0000e+00])
torch.Size([64000])
pitch: 84
velocity: 127
family:8
label:854
source:0
tf.Tensor([64000], shape

In [65]:
from IPython.display import Audio
import random
import math

In [69]:
Audio(numpy_temp, rate = 16000)

In [89]:
import numpy as np
from scipy.io.wavfile import write
import librosa
import librosa.display
import soundfile as sf

def save_mono_to_wav(audio_array, pitch, velocity, output_folder="/content/drive/MyDrive/DeBaussyAI/Training Data/NSynth Extractions", sample_rate=16000):
  # Use soundfile to save the reconstructed audio as WAV (since soundfile does not support MP3)
  print("YAUR")
  wav_path = output_folder + r"/" + str(pitch) + "_" + str(velocity) + ".wav"
  write(wav_path, sample_rate, audio_array)

In [96]:
import torch
import numpy as np

# Searches for files to download (0 means acoustic and 8 means strings)
i = 0
for example in dataset['train']:
  if i >= 500:
    break
  if (example["instrument"]["source"] == 0) and (example["instrument"]["family"] == 8):
    i += 1
    # print(f'pitch: {example["pitch"]}')
    # print(f'velocity: {example["velocity"]}')
    # for key in example['instrument'].keys():
    #   print(f"{key}:{example['instrument'][key]}")
    # print(tf.shape(example['audio']))
    # print(example["audio"])
    tf_tensor = example['audio']
    # print(tf_tensor.shape)
    numpy_temp = tf_tensor.numpy()
    audio_array = numpy_temp
    pitch = int(example["pitch"].numpy())
    velocity = int(example["velocity"].numpy())
    save_mono_to_wav(audio_array, pitch, velocity)
    # print(numpy_temp)
    # torch_tensor = torch.from_numpy(numpy_temp)
    # print(torch_tensor)
    # print(torch_tensor.shape)

YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR
YAUR


In [91]:
Audio('/content/drive/MyDrive/DeBaussyAI/Training Data/NSynth Extractions/tf.Tensor(37, shape=(), dtype=int64)_tf.Tensor(75, shape=(), dtype=int64).wav',rate=16000)

In [ ]:
testing = []
for i in range(50000):
  testing.append(math.cos(440*i)*100000)
Audio(testing, rate=22050)

In [37]:
import json
import shutil
import os

In [ ]:
# Paths to dataset
dataset_dir = "/content/nsynth-train"  # Replace with the dataset directory
json_path = os.path.join(dataset_dir, "train.json")  # Adjust for "valid.json" or "test.json" if needed
audio_dir = os.path.join(dataset_dir, "audio")
output_dir = "/content/drive/MyDrive/DeBaussyAI/Training Data/NSynth Data Extractions"  # Replace with desired output directory for acoustic strings

# Create output directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# Load metadata
with open(json_path, "r") as f:
    metadata = json.load(f)

# Filter acoustic strings
filtered_files = []
for note_id, attributes in metadata.items():
    if attributes["instrument_source_str"] == "acoustic" and attributes["instrument_family_str"] == "string":
        filtered_files.append(attributes["note_str"])

# Copy filtered audio files to output directory
for file_name in filtered_files:
    src_path = os.path.join(audio_dir, file_name + ".wav")
    dst_path = os.path.join(output_dir, file_name + ".wav")
    if os.path.exists(src_path):
        shutil.copy(src_path, dst_path)
        print(f"Copied: {file_name}.wav")

print(f"Extracted {len(filtered_files)} acoustic string audio files to {output_dir}")


FileNotFoundError: [Errno 2] No such file or directory: '/content/nsynth-train/train.json'

In [ ]:
!ls


drive  nsynth-train  nsynth-train.jsonwav.tar.gz  sample_data


In [ ]:
!mkdir /content/acoustic_strings


In [ ]:
!find . -type f -iname "*acoustic_string*.wav" -exec mv {} /content/acoustic_strings/ \;

In [ ]:
!ls

acoustic_strings  drive  nsynth-train  nsynth-train.jsonwav.tar.gz  sample_data


In [ ]:
!du -sh /content/acoustic_strings

4.0K	/content/acoustic_strings


In [ ]:
import os
import shutil

source_dir = '/content/nsynth-train/audio'  # Change path based on where the audio files are
dest_dir = '/content/drive/MyDrive/DeBaussyAI/Training Data/NSynth Data Extractions'

# Loop through all files in the source directory
for file_name in os.listdir(source_dir):
    if 'keyboard_electronic' in file_name:
        print("yaur")
        shutil.copy(os.path.join(source_dir, file_name), os.path.join(dest_dir, file_name))

# Check the contents of the destination directory again
!ls "/content/drive/MyDrive/DeBaussyAI/Training Data/NSynth Data Extractions"

yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur
yaur


KeyboardInterrupt: 

In [ ]:
!ls "/content/drive/MyDrive/DeBaussyAI/Training Data/NSynth Data Extractions"

keyboard_electronic_000-029-100.wav  keyboard_electronic_053-035-100.wav
keyboard_electronic_000-029-127.wav  keyboard_electronic_053-038-025.wav
keyboard_electronic_000-030-127.wav  keyboard_electronic_053-044-075.wav
keyboard_electronic_000-033-025.wav  keyboard_electronic_053-052-075.wav
keyboard_electronic_000-098-127.wav  keyboard_electronic_053-071-075.wav
keyboard_electronic_000-101-127.wav  keyboard_electronic_053-079-100.wav
keyboard_electronic_004-023-025.wav  keyboard_electronic_053-081-050.wav
keyboard_electronic_004-027-025.wav  keyboard_electronic_053-088-050.wav
keyboard_electronic_004-040-100.wav  keyboard_electronic_054-021-075.wav
keyboard_electronic_004-051-127.wav  keyboard_electronic_054-035-075.wav
keyboard_electronic_004-069-025.wav  keyboard_electronic_054-037-075.wav
keyboard_electronic_004-069-100.wav  keyboard_electronic_054-042-127.wav
keyboard_electronic_004-092-075.wav  keyboard_electronic_054-100-050.wav
keyboard_electronic_004-096-075.wav  keyboard_elect

In [ ]:
!ls '/content/nsynth-train/audio'

Streaming output truncated to the last 5000 lines.
keyboard_electronic_031-072-100.wav  vocal_synthetic_002-094-127.wav
keyboard_electronic_031-072-127.wav  vocal_synthetic_002-095-025.wav
keyboard_electronic_031-073-025.wav  vocal_synthetic_002-095-050.wav
keyboard_electronic_031-073-050.wav  vocal_synthetic_002-095-075.wav
keyboard_electronic_031-073-075.wav  vocal_synthetic_002-095-100.wav
keyboard_electronic_031-073-100.wav  vocal_synthetic_002-095-127.wav
keyboard_electronic_031-073-127.wav  vocal_synthetic_002-096-025.wav
keyboard_electronic_031-074-025.wav  vocal_synthetic_002-096-050.wav
keyboard_electronic_031-074-050.wav  vocal_synthetic_002-096-075.wav
keyboard_electronic_031-074-075.wav  vocal_synthetic_002-096-100.wav
keyboard_electronic_031-074-100.wav  vocal_synthetic_002-096-127.wav
keyboard_electronic_031-074-127.wav  vocal_synthetic_002-097-025.wav
keyboard_electronic_031-075-025.wav  vocal_synthetic_002-097-050.wav
keyboard_electronic_031-075-050.wav  vocal_synthetic